futures = data.frame("Front Month" = character(),"Price" = integer())
cl1 = data.frame("Front_Month" = 1,"Price" = Quandl("CHRIS/CME_CL1", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl2 = data.frame("Front_Month" = 2,"Price" = Quandl("CHRIS/CME_CL2", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl3 = data.frame("Front_Month" = 3,"Price" = Quandl("CHRIS/CME_CL3", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl4 = data.frame("Front_Month" = 4,"Price" = Quandl("CHRIS/CME_CL4", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl5 = data.frame("Front_Month" = 5,"Price" = Quandl("CHRIS/CME_CL5", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl6 = data.frame("Front_Month" = 6,"Price" = Quandl("CHRIS/CME_CL6", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl7 = data.frame("Front_Month" = 7,"Price" = Quandl("CHRIS/CME_CL7", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl8 = data.frame("Front_Month" = 8,"Price" = Quandl("CHRIS/CME_CL8", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl9 = data.frame("Front_Month" = 10,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl9 = data.frame("Front_Month" = 10,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl10 = data.frame("Front_Month" = 11,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl11 = data.frame("Front_Month" = 12,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl12 = data.frame("Front_Month" = 13,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl13 = data.frame("Front_Month" = 14,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl14 = data.frame("Front_Month" = 15,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl15 = data.frame("Front_Month" = 16,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl16 = data.frame("Front_Month" = 17,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl17 = data.frame("Front_Month" = 18,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl18 = data.frame("Front_Month" = 19,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])
cl19 = data.frame("Front_Month" = 20,"Price" = Quandl("CHRIS/CME_CL9", api_key="Xa-XyezxZxsEZpmhKYkt", start_date=Sys.Date()-days(1))[,5])

futures = rbind(futures,cl1,cl2,cl3,cl4,cl5,cl6,cl7,cl8,cl9)
